package org.scottishtecharmy.soundscape.geoengine.journey

import org.scottishtecharmy.soundscape.geojsonparser.geojson.LngLatAlt

/**
 * One thing worth remembering about a journey as it happens, so that the user can afterwards turn
 * the journey into a Route.
 *
 * These are *derived* events, not GPS fixes - a few dozen per journey rather than one a second -
 * which is what makes the recording cheap enough to leave running all the time. See JourneyRecorder
 * for the recording itself, and GpxRecorder for the separate developer diagnostic that does keep
 * every fix.
 *
 * Everything spoken here is resolved in the user's language *as the journey happens*. It has to be:
 * by the time the user saves, the tile grid has moved on and the Ways the names came from no longer
 * exist.
 */
sealed class JourneyEvent {
    abstract val timestampMillis: Long
    abstract val location: LngLatAlt

    /**
     * A downsampled position along the path. Used only to work out where one journey ends and the
     * next begins, and to place the route's start and destination - the path itself is deliberately
     * never persisted.
     */
    data class Anchor(
        override val location: LngLatAlt,
        override val timestampMillis: Long,
        val speedMps: Double,
        val inVehicle: Boolean,
    ) : JourneyEvent()

    /**
     * An intersection the user did not go straight through - the raw material of a turn-by-turn
     * instruction.
     *
     * [signedAngleDegrees] is negative for a left turn and positive for a right one, which is what
     * lets the reverse wording be generated by flipping the sign and swapping the two road names.
     */
    data class Turn(
        override val location: LngLatAlt,
        override val timestampMillis: Long,
        /** The road being left, named in the direction it was travelled. */
        val fromRoad: String,
        /** The road being joined, named in the direction it is about to be travelled. */
        val toRoad: String,
        val signedAngleDegrees: Double,
        /** Whether this was taken by bus, train or car rather than on foot - see [Alighting]. */
        val inVehicle: Boolean = false,
    ) : JourneyEvent()

    /**
     * A named place the app called out as the user went past.
     *
     * [location] is where the *user* was, not where the place is. A vehicle landmark is announced
     * up to 150m away and a walking POI is located at the nearest point on the feature itself, so
     * using the feature's own position would put a replaying user's beacon off the road, aimed at a
     * shop they merely walked past. "You passed X here" is the useful meaning for a route.
     */
    data class Landmark(
        override val location: LngLatAlt,
        override val timestampMillis: Long,
        val name: String,
        /** Whether this went past at vehicle speed rather than walking pace - see [Alighting]. */
        val inVehicle: Boolean = false,
    ) : JourneyEvent()

    /**
     * Where the user left the bus, train or car and carried on walking.
     *
     * A leg travelled at speed gets no waypoints of its own. You can't walk to a landmark you were
     * driven past, and turns the bus took aren't yours to take - what you need is one beacon on the
     * stop you got off at, with the walk either side of it marked as walks are. So the route reads:
     * the way to the stop, one waypoint where the ride ended, then the way on from there.
     */
    data class Alighting(
        override val location: LngLatAlt,
        override val timestampMillis: Long,
        /** The stop, where one was announced during the ride, or null to name it generically. */
        val stopName: String?,
    ) : JourneyEvent()
}
